global:
  scrape_interval:     15s # Default is every 1 minute.
  evaluation_interval: 15s # Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['127.0.0.1:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']